spring.application.name=api
server.servlet.context-path=/api

spring.datasource.url=jdbc:postgresql://localhost:5432/irontrail
spring.datasource.username=${DB_USERNAME:irontrail}
spring.datasource.password=${DB_PASSWORD:irontrail_dev}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true